# Generated by Django 5.2.5 on 2025-08-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('merchant', 'Merchant')], default='customer', max_length=10),
        ),
    ]
