# Generated by Django 5.2.5 on 2025-08-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_seats_alter_booking_total_price_and_more'),
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveloption',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_options', to='merchant.bus'),
        ),
    ]
