# Generated by Django 5.2.5 on 2025-08-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_traveloption_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveloption',
            name='bus',
        ),
    ]
