# Generated by Django 5.2.5 on 2025-08-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_traveloption_bus'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travel_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.traveloption'),
        ),
        migrations.DeleteModel(
            name='TravelOption',
        ),
    ]
