# Generated by Django 5.2.5 on 2025-08-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus')], max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_seats', models.PositiveIntegerField()),
                ('repeat_days', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('train_number', models.CharField(blank=True, max_length=50, null=True)),
                ('coach_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='travel_options', to='merchant.bus')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_options', to='merchant.merchantprofile')),
            ],
        ),
    ]
